# Medium Tests: Run on all commits/PRs to dev branch

language: c
sudo: required
dist: trusty
matrix:
  include:
    # OS X Mavericks
    - env: Cmd="make test"
      os: osx

before_install:
  - if [ `uname` = "Darwin" ]; then brew update; fi

install:
  - if [ `uname` = "Darwin" ]; then brew install xz; fi

git:
  depth: 1

branches:
  only:
  - dev
  - master
  - testing

script:
  - JOB_NUMBER=$(echo $TRAVIS_JOB_NUMBER | sed -e 's:[0-9][0-9]*\.\(.*\):\1:')
  - echo JOB_NUMBER=$JOB_NUMBER TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
  - export FUZZERTEST=-T2mn;
    export ZSTREAM_TESTTIME=-T2mn;
    export DECODECORPUS_TESTTIME=-T1mn;
    sh -c "$Cmd" || travis_terminate 1;
